### ISSUE TITLE
SARS-CoV-2 workflow comparison - kindly check if your work is represented correctly

### ISSUE THREAD

**Issue by thomasbtf** [andersen-lab/bjorn#50]
Hello bjorn Team,

I am from the University Hospital Essen, Germany, and we work extensively with SARS-CoV-2 in our research. We have also developed a [SARS-CoV-2 workflow](https://github.com/IKIM-Essen/uncovar). In preparation for the publication of our workflow, we have looked at several other SARS-CoV-2 related workflows, including your work. We will present this review in the publication and want to ensure that your work is represented as accurately as possible.

Moreover, there is currently little to no current overview of SARS-CoV-2 related workflows. Therefore, we have decided to make the above comparison publicly available [via this GitHub repository](https://github.com/IKIM-Essen/sars-cov-2-workflow-comparison). It contains a table with an overview of the functions of different SARS-CoV-2 workflows and the tools used to implement these functions.

We would like to give you the opportunity to correct any misunderstandings on our side. Please take a moment to make sure we are not misrepresenting your work or leaving out important parts of it by taking a look at [this overview table](https://github.com/IKIM-Essen/sars-cov-2-workflow-comparison/blob/main/workflow-overview.md). If you feel that something is missing or misrepresented, please feel free to give us feedback by contributing directly to the repository.

Thank you very much!

cc @alethomas

**Comment by flaneuse** [comment]
Thanks @thomasbtf and @alethomas. I don't think anything is misrepresented in your table, but I would question if Bjorn should be included, since it's trying to solve a different problem than the other tools that you listed. Bjorn is not meant for the processing of primary data, but rather is a pipeline for counting SARS-CoV-2 mutations from a set of sequences.  Please let us know if you have other questions.

**Comment by thomasbtf** [comment]
Hi Laura,

thanks for checking! I`ve just added your comment with the counting to the bjorn entry in https://github.com/IKIM-Essen/sars-cov-2-workflow-comparison/pull/16.
If it's alright with you, we would love to keep bjorn in the table, as it is a valuable resource for SARS-CoV-2 analysis. Are you okay with that? :)

**Comment by gkarthik** [comment]
Hey @thomasbtf , should be fine to keep it in! I think the comment makes it clear that bjorn is meant for counting mutations. This is a very helpful overview, thank you for putting this together!

**Comment by thomasbtf** [comment]
Hey @gkarthik, awesome, then we will keep in the overview. Cheers!
